### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ShootToKillSTK** [CodexAdrian/Spirit#11]
Launcher crashes almost instantly after pressing play in 1.18.2 version of the mod, tested without out any other mods too (Doesn't give crash log so here is normal log)

[latest.log](https://github.com/CodexAdrian/Spirit/files/8240694/latest.log)

**Comment by CodexAdrian** [comment]
Please specify launcher version

**Comment by FynnWaelsing** [comment]
I'm getting the same crash with Forge 40.0.15 using both GDLauncher and MultiMC. Here's the log from MMC: https://pastebin.com/nEeXAqbY

**Comment by ShootToKillSTK** [comment]
I was using Forge 40.0.12, curseforge launcher but I believe I tried other versions too of 1.18.2 Forge's

**Comment by CodexAdrian** [comment]
This is now fixed in 1.2.1

**Comment by CodexAdrian** [comment]
I should clarify, this repo is no longer active. https://github.com/Toadstool-Studios/Spirit is now the active repo
