### ISSUE TITLE
Custom Higher Tiers

### ISSUE THREAD

**Issue by theendercore** [CodexAdrian/Spirit#2]
There seams to be a problem with the ability to set custom tiers for soul crystals. It doesn't seam to go past tier 4 for some reason. 

I am using Spirit version 1.0.5 (the latest version), and I am on Minecraft 1.17.1

**Comment by CodexAdrian** [comment]
It is capped at 4, you can make it have less than 4 tiers but its coded to not allow you to make more than 4, I might change that in the future but at the moment this is an intended design choice
