### ISSUE TITLE
Placing a Block on the spawner remove's the crystal

### ISSUE THREAD

**Issue by theendercore** [CodexAdrian/Spirit#4]
When placing a block on the spawner it remove's the crystal. 
![gifpp-min](https://user-images.githubusercontent.com/49921297/127894669-5114bb46-4a68-4e3c-acd2-fa53d9fc33e4.gif)

I am using Spirit version 1.0.5 (the latest version), and I am on Minecraft 1.17.1

**Comment by CodexAdrian** [comment]
This seems like a non-issue.. just don't do that
