### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by SharkieTV** [CodexAdrian/Spirit#5]
**Possible issue with memory leak on Spirit mod?**
Some players have reported that they lag incredibly when using the soul cage, it does mention sodium in there but after removing iris shaders it still lags even with 10gb memory allocated.
https://pastebin.com/ruRPFd6K

**Comment by ZizzyDizzyMC** [comment]
I have confirmed there is a memory leak with the glowing effects of mobs / the spawned mobs.  Killing the mobs fixes the issue.  

Memory leak is client side only, server side appears to be stable.

**Comment by PenguVoid** [comment]
Can confirm as well, build a wither on our server and our clients just started crashing when near it, breaking it and killing off all the mobs fixed it.
also when crashing the logs stated and "out of memory" error for all of us

**Comment by CodexAdrian** [comment]
After looking it over, and asking several friends to take a look, it doesn't seem as though Spirit is creating a memory leak. At least it doesn't seem to be present in Spirit without Sodium present, and my computer seems to be unable to run Sodium so I cannot test it with that. I will try to do further testing, but at the moment it doesn't seem as though Spirit is causing a memory leak. I'll keep this issue open for now

**Comment by CodexAdrian** [comment]
This issue seems to be caused by Iris, as we cannot replicate the memory leak without Iris present.
