### ISSUE TITLE
how do u make a working spanwer

### ISSUE THREAD

**Issue by undeads1ayer** [CodexAdrian/Spirit#6]

**Comment by CodexAdrian** [comment]
Get a crystal to at least tier 1 (the values for that are on the CF page) and then place the crystal in the spawner by right clicking it. The spawn requirements of the mob must be met to spawn a mob, so make sure you're following those. Then you should be good to go, I will make a wiki page soon

**Comment by undeads1ayer** [comment]
Ok thank you for responding 😁
