### ISSUE TITLE
Iron Golem Spawner doesn't work

### ISSUE THREAD

**Issue by GudPiggeh** [CodexAdrian/Spirit#9]
I believe it is related to https://bugs.mojang.com/browse/MC-144062. The checkSpawnObstruction override for Iron Golem also checks for opaque blocks, which is a bug in vanilla which doesn't usually occur since they're not possible without commands.

**Comment by CodexAdrian** [comment]
You can now set the spawner to ignore spawn conditions, this should allow you to spawn iron golems at higher tiers. I might make it so you can configure certain mobs to always ignore spawn conditions, like neutral mobs or the iron golem, but thats not going to be implemented anytime soon.
